### ISSUE TITLE
Error occurred when executing Stage1_load: No module named 'ComfyUI-DiffBIR'

### ISSUE THREAD

**Issue by kkde73** [jtscmw01/ComfyUI-DiffBIR#2]
Hello,

I followed the installation instructions for steps 1 and 2, but encountered the following error while executing the workflow in ComfyUI:

"Error occurred when executing Stage1_load:

No module named 'ComfyUI-DiffBIR''"

Could you please advise on how to resolve this issue?

Best regards

**Comment by kkde73** [comment]
I've figured out the issue. 

After downloading the files, the directory name automatically becomes **ComfyUI-DiffBIR-main**, requiring manual renaming to **ComfyUI-DiffBIR**.

**Comment by suntao77777** [comment]
thank you very much
